/*
 * TD Ameritrade API - OAuth2
 * This is replication of the TD Ameritrade API.
 *
 * OpenAPI spec version: 0.1.4
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.14
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GitChrisQueen_TDA_JS);
  }
}(this, function(expect, GitChrisQueen_TDA_JS) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new GitChrisQueen_TDA_JS.MoversApi();
  });

  describe('(package)', function() {
    describe('MoversApi', function() {
      describe('marketdataIndexMoversGET', function() {
        it('should call marketdataIndexMoversGET successfully', function(done) {
          // TODO: uncomment, update parameter values for marketdataIndexMoversGET call and complete the assertions
          /*
          var index = "index_example";
          var opts = {};
          opts.apikey = "apikey_example";
          opts.direction = "direction_example";
          opts.change = "change_example";

          instance.marketdataIndexMoversGET(index, opts).then(function(data) {
            // TODO: update response assertions
            expect(data).to.be.a(GitChrisQueen_TDA_JS.Mover);
            expect(data.change).to.be.a('number');
            expect(data.change).to.be(0.0);
            expect(data.description).to.be.a('string');
            expect(data.description).to.be("");
            expect(data.direction).to.be.a('string');
            expect(data.direction).to.be("up");
            expect(data.last).to.be.a('number');
            expect(data.last).to.be(0.0);
            expect(data.symbol).to.be.a('string');
            expect(data.symbol).to.be("");
            expect(data.totalVolume).to.be.a('number');
            expect(data.totalVolume).to.be("0");

            done();
          }, function(error) {
            done(error);
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
