/*
 * TD Ameritrade API - OAuth2
 * This is replication of the TD Ameritrade API.
 *
 * OpenAPI spec version: 0.1.4
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.14
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GitChrisQueen_TDA_JS);
  }
}(this, function(expect, GitChrisQueen_TDA_JS) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new GitChrisQueen_TDA_JS.QuotesApi();
  });

  describe('(package)', function() {
    describe('QuotesApi', function() {
      describe('marketdataQuotesGET', function() {
        it('should call marketdataQuotesGET successfully', function(done) {
          // TODO: uncomment, update parameter values for marketdataQuotesGET call and complete the assertions
          /*
          var opts = {};
          opts.apikey = "apikey_example";
          opts.symbol = "symbol_example";

          instance.marketdataQuotesGET(opts).then(function(data) {
            // TODO: update response assertions
            expect(data).to.be.a(GitChrisQueen_TDA_JS.GetQuoteResponse);

            done();
          }, function(error) {
            done(error);
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('marketdataSymbolQuotesGET', function() {
        it('should call marketdataSymbolQuotesGET successfully', function(done) {
          // TODO: uncomment, update parameter values for marketdataSymbolQuotesGET call and complete the assertions
          /*
          var symbol = "symbol_example";
          var opts = {};
          opts.apikey = "apikey_example";

          instance.marketdataSymbolQuotesGET(symbol, opts).then(function(data) {
            // TODO: update response assertions
            expect(data).to.be.a(GitChrisQueen_TDA_JS.GetQuoteResponse);

            done();
          }, function(error) {
            done(error);
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
