/**
 * TD Ameritrade API - OAuth2
 * This is replication of the TD Ameritrade API.
 *
 * OpenAPI spec version: 0.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AccountSecuritiesAccount from './AccountSecuritiesAccount';

/**
* The Account model module.
* @module model/Account
* @version 0.1.4
*/
export default class Account {
    /**
    * Constructs a new <code>Account</code>.
    * @alias module:model/Account
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>Account</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Account} obj Optional instance to populate.
    * @return {module:model/Account} The populated <code>Account</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Account();
                        
            
            if (data.hasOwnProperty('securitiesAccount')) {
                obj['securitiesAccount'] = AccountSecuritiesAccount.constructFromObject(data['securitiesAccount']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/AccountSecuritiesAccount} securitiesAccount
    */
    'securitiesAccount' = undefined;




}
