/**
 * TD Ameritrade API - OAuth2
 * This is replication of the TD Ameritrade API.
 *
 * OpenAPI spec version: 0.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The CashAccountBalances model module.
* @module model/CashAccountBalances
* @version 0.1.4
*/
export default class CashAccountBalances {
    /**
    * Constructs a new <code>CashAccountBalances</code>.
    * @alias module:model/CashAccountBalances
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>CashAccountBalances</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/CashAccountBalances} obj Optional instance to populate.
    * @return {module:model/CashAccountBalances} The populated <code>CashAccountBalances</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CashAccountBalances();
                        
            
            if (data.hasOwnProperty('accruedInterest')) {
                obj['accruedInterest'] = ApiClient.convertToType(data['accruedInterest'], 'Number');
            }
            if (data.hasOwnProperty('cashBalance')) {
                obj['cashBalance'] = ApiClient.convertToType(data['cashBalance'], 'Number');
            }
            if (data.hasOwnProperty('cashReceipts')) {
                obj['cashReceipts'] = ApiClient.convertToType(data['cashReceipts'], 'Number');
            }
            if (data.hasOwnProperty('longOptionMarketValue')) {
                obj['longOptionMarketValue'] = ApiClient.convertToType(data['longOptionMarketValue'], 'Number');
            }
            if (data.hasOwnProperty('liquidationValue')) {
                obj['liquidationValue'] = ApiClient.convertToType(data['liquidationValue'], 'Number');
            }
            if (data.hasOwnProperty('longMarketValue')) {
                obj['longMarketValue'] = ApiClient.convertToType(data['longMarketValue'], 'Number');
            }
            if (data.hasOwnProperty('moneyMarketFund')) {
                obj['moneyMarketFund'] = ApiClient.convertToType(data['moneyMarketFund'], 'Number');
            }
            if (data.hasOwnProperty('savings')) {
                obj['savings'] = ApiClient.convertToType(data['savings'], 'Number');
            }
            if (data.hasOwnProperty('shortMarketValue')) {
                obj['shortMarketValue'] = ApiClient.convertToType(data['shortMarketValue'], 'Number');
            }
            if (data.hasOwnProperty('pendingDeposits')) {
                obj['pendingDeposits'] = ApiClient.convertToType(data['pendingDeposits'], 'Number');
            }
            if (data.hasOwnProperty('cashAvailableForTrading')) {
                obj['cashAvailableForTrading'] = ApiClient.convertToType(data['cashAvailableForTrading'], 'Number');
            }
            if (data.hasOwnProperty('cashAvailableForWithdrawal')) {
                obj['cashAvailableForWithdrawal'] = ApiClient.convertToType(data['cashAvailableForWithdrawal'], 'Number');
            }
            if (data.hasOwnProperty('cashCall')) {
                obj['cashCall'] = ApiClient.convertToType(data['cashCall'], 'Number');
            }
            if (data.hasOwnProperty('longNonMarginableMarketValue')) {
                obj['longNonMarginableMarketValue'] = ApiClient.convertToType(data['longNonMarginableMarketValue'], 'Number');
            }
            if (data.hasOwnProperty('totalCash')) {
                obj['totalCash'] = ApiClient.convertToType(data['totalCash'], 'Number');
            }
            if (data.hasOwnProperty('shortOptionMarketValue')) {
                obj['shortOptionMarketValue'] = ApiClient.convertToType(data['shortOptionMarketValue'], 'Number');
            }
            if (data.hasOwnProperty('mutualFundValue')) {
                obj['mutualFundValue'] = ApiClient.convertToType(data['mutualFundValue'], 'Number');
            }
            if (data.hasOwnProperty('bondValue')) {
                obj['bondValue'] = ApiClient.convertToType(data['bondValue'], 'Number');
            }
            if (data.hasOwnProperty('cashDebitCallValue')) {
                obj['cashDebitCallValue'] = ApiClient.convertToType(data['cashDebitCallValue'], 'Number');
            }
            if (data.hasOwnProperty('unsettledCash')) {
                obj['unsettledCash'] = ApiClient.convertToType(data['unsettledCash'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {Number} accruedInterest
    */
    'accruedInterest' = undefined;
    /**
    * @member {Number} cashBalance
    */
    'cashBalance' = undefined;
    /**
    * @member {Number} cashReceipts
    */
    'cashReceipts' = undefined;
    /**
    * @member {Number} longOptionMarketValue
    */
    'longOptionMarketValue' = undefined;
    /**
    * @member {Number} liquidationValue
    */
    'liquidationValue' = undefined;
    /**
    * @member {Number} longMarketValue
    */
    'longMarketValue' = undefined;
    /**
    * @member {Number} moneyMarketFund
    */
    'moneyMarketFund' = undefined;
    /**
    * @member {Number} savings
    */
    'savings' = undefined;
    /**
    * @member {Number} shortMarketValue
    */
    'shortMarketValue' = undefined;
    /**
    * @member {Number} pendingDeposits
    */
    'pendingDeposits' = undefined;
    /**
    * @member {Number} cashAvailableForTrading
    */
    'cashAvailableForTrading' = undefined;
    /**
    * @member {Number} cashAvailableForWithdrawal
    */
    'cashAvailableForWithdrawal' = undefined;
    /**
    * @member {Number} cashCall
    */
    'cashCall' = undefined;
    /**
    * @member {Number} longNonMarginableMarketValue
    */
    'longNonMarginableMarketValue' = undefined;
    /**
    * @member {Number} totalCash
    */
    'totalCash' = undefined;
    /**
    * @member {Number} shortOptionMarketValue
    */
    'shortOptionMarketValue' = undefined;
    /**
    * @member {Number} mutualFundValue
    */
    'mutualFundValue' = undefined;
    /**
    * @member {Number} bondValue
    */
    'bondValue' = undefined;
    /**
    * @member {Number} cashDebitCallValue
    */
    'cashDebitCallValue' = undefined;
    /**
    * @member {Number} unsettledCash
    */
    'unsettledCash' = undefined;




}
