/**
 * TD Ameritrade API - OAuth2
 * This is replication of the TD Ameritrade API.
 *
 * OpenAPI spec version: 0.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The ForexQuote model module.
* @module model/ForexQuote
* @version 0.1.4
*/
export default class ForexQuote {
    /**
    * Constructs a new <code>ForexQuote</code>.
    * @alias module:model/ForexQuote
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>ForexQuote</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ForexQuote} obj Optional instance to populate.
    * @return {module:model/ForexQuote} The populated <code>ForexQuote</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ForexQuote();
                        
            
            if (data.hasOwnProperty('symbol')) {
                obj['symbol'] = ApiClient.convertToType(data['symbol'], 'String');
            }
            if (data.hasOwnProperty('bidPriceInDouble')) {
                obj['bidPriceInDouble'] = ApiClient.convertToType(data['bidPriceInDouble'], 'Number');
            }
            if (data.hasOwnProperty('askPriceInDouble')) {
                obj['askPriceInDouble'] = ApiClient.convertToType(data['askPriceInDouble'], 'Number');
            }
            if (data.hasOwnProperty('lastPriceInDouble')) {
                obj['lastPriceInDouble'] = ApiClient.convertToType(data['lastPriceInDouble'], 'Number');
            }
            if (data.hasOwnProperty('highPriceInDouble')) {
                obj['highPriceInDouble'] = ApiClient.convertToType(data['highPriceInDouble'], 'Number');
            }
            if (data.hasOwnProperty('lowPriceInDouble')) {
                obj['lowPriceInDouble'] = ApiClient.convertToType(data['lowPriceInDouble'], 'Number');
            }
            if (data.hasOwnProperty('closePriceInDouble')) {
                obj['closePriceInDouble'] = ApiClient.convertToType(data['closePriceInDouble'], 'Number');
            }
            if (data.hasOwnProperty('exchange')) {
                obj['exchange'] = ApiClient.convertToType(data['exchange'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('openPriceInDouble')) {
                obj['openPriceInDouble'] = ApiClient.convertToType(data['openPriceInDouble'], 'Number');
            }
            if (data.hasOwnProperty('changeInDouble')) {
                obj['changeInDouble'] = ApiClient.convertToType(data['changeInDouble'], 'Number');
            }
            if (data.hasOwnProperty('percentChange')) {
                obj['percentChange'] = ApiClient.convertToType(data['percentChange'], 'Number');
            }
            if (data.hasOwnProperty('exchangeName')) {
                obj['exchangeName'] = ApiClient.convertToType(data['exchangeName'], 'String');
            }
            if (data.hasOwnProperty('digits')) {
                obj['digits'] = ApiClient.convertToType(data['digits'], 'Number');
            }
            if (data.hasOwnProperty('securityStatus')) {
                obj['securityStatus'] = ApiClient.convertToType(data['securityStatus'], 'String');
            }
            if (data.hasOwnProperty('tick')) {
                obj['tick'] = ApiClient.convertToType(data['tick'], 'Number');
            }
            if (data.hasOwnProperty('tickAmount')) {
                obj['tickAmount'] = ApiClient.convertToType(data['tickAmount'], 'Number');
            }
            if (data.hasOwnProperty('product')) {
                obj['product'] = ApiClient.convertToType(data['product'], 'String');
            }
            if (data.hasOwnProperty('tradingHours')) {
                obj['tradingHours'] = ApiClient.convertToType(data['tradingHours'], 'String');
            }
            if (data.hasOwnProperty('isTradable')) {
                obj['isTradable'] = ApiClient.convertToType(data['isTradable'], 'Boolean');
            }
            if (data.hasOwnProperty('marketMaker')) {
                obj['marketMaker'] = ApiClient.convertToType(data['marketMaker'], 'String');
            }
            if (data.hasOwnProperty('52WkHighInDouble')) {
                obj['52WkHighInDouble'] = ApiClient.convertToType(data['52WkHighInDouble'], 'Number');
            }
            if (data.hasOwnProperty('52WkLowInDouble')) {
                obj['52WkLowInDouble'] = ApiClient.convertToType(data['52WkLowInDouble'], 'Number');
            }
            if (data.hasOwnProperty('mark')) {
                obj['mark'] = ApiClient.convertToType(data['mark'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {String} symbol
    */
    'symbol' = undefined;
    /**
    * @member {Number} bidPriceInDouble
    */
    'bidPriceInDouble' = undefined;
    /**
    * @member {Number} askPriceInDouble
    */
    'askPriceInDouble' = undefined;
    /**
    * @member {Number} lastPriceInDouble
    */
    'lastPriceInDouble' = undefined;
    /**
    * @member {Number} highPriceInDouble
    */
    'highPriceInDouble' = undefined;
    /**
    * @member {Number} lowPriceInDouble
    */
    'lowPriceInDouble' = undefined;
    /**
    * @member {Number} closePriceInDouble
    */
    'closePriceInDouble' = undefined;
    /**
    * @member {String} exchange
    */
    'exchange' = undefined;
    /**
    * @member {String} description
    */
    'description' = undefined;
    /**
    * @member {Number} openPriceInDouble
    */
    'openPriceInDouble' = undefined;
    /**
    * @member {Number} changeInDouble
    */
    'changeInDouble' = undefined;
    /**
    * @member {Number} percentChange
    */
    'percentChange' = undefined;
    /**
    * @member {String} exchangeName
    */
    'exchangeName' = undefined;
    /**
    * @member {Number} digits
    */
    'digits' = undefined;
    /**
    * @member {String} securityStatus
    */
    'securityStatus' = undefined;
    /**
    * @member {Number} tick
    */
    'tick' = undefined;
    /**
    * @member {Number} tickAmount
    */
    'tickAmount' = undefined;
    /**
    * @member {String} product
    */
    'product' = undefined;
    /**
    * @member {String} tradingHours
    */
    'tradingHours' = undefined;
    /**
    * @member {Boolean} isTradable
    */
    'isTradable' = undefined;
    /**
    * @member {String} marketMaker
    */
    'marketMaker' = undefined;
    /**
    * @member {Number} 52WkHighInDouble
    */
    '52WkHighInDouble' = undefined;
    /**
    * @member {Number} 52WkLowInDouble
    */
    '52WkLowInDouble' = undefined;
    /**
    * @member {Number} mark
    */
    'mark' = undefined;




}
