/**
 * TD Ameritrade API - OAuth2
 * This is replication of the TD Ameritrade API.
 *
 * OpenAPI spec version: 0.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The GetQuoteResponse model module.
* @module model/GetQuoteResponse
* @version 0.1.4
*/
export default class GetQuoteResponse {
    /**
    * Constructs a new <code>GetQuoteResponse</code>.
    * @alias module:model/GetQuoteResponse
    * @class
    * @extends Object
    */

    constructor() {
        
        
        return this;
    }

    /**
    * Constructs a <code>GetQuoteResponse</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/GetQuoteResponse} obj Optional instance to populate.
    * @return {module:model/GetQuoteResponse} The populated <code>GetQuoteResponse</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetQuoteResponse();
            ApiClient.constructFromObject(data, obj, 'Object');
            
            
        }
        return obj;
    }





}
