/**
 * TD Ameritrade API - OAuth2
 * This is replication of the TD Ameritrade API.
 *
 * OpenAPI spec version: 0.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ModelObject from './ModelObject';

/**
* The Instrument model module.
* @module model/Instrument
* @version 0.1.4
*/
export default class Instrument {
    /**
    * Constructs a new <code>Instrument</code>.
    * @alias module:model/Instrument
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>Instrument</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Instrument} obj Optional instance to populate.
    * @return {module:model/Instrument} The populated <code>Instrument</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Instrument();
                        
            
            if (data.hasOwnProperty('schema')) {
                obj['schema'] = ApiClient.convertToType(data['schema'], ModelObject);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/ModelObject} schema
    */
    'schema' = undefined;




}
