/**
 * TD Ameritrade API - OAuth2
 * This is replication of the TD Ameritrade API.
 *
 * OpenAPI spec version: 0.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MarginAccountBalances from './MarginAccountBalances';

/**
* The MarginAccountCurrentBalances model module.
* @module model/MarginAccountCurrentBalances
* @version 0.1.4
*/
export default class MarginAccountCurrentBalances {
    /**
    * Constructs a new <code>MarginAccountCurrentBalances</code>.
    * @alias module:model/MarginAccountCurrentBalances
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>MarginAccountCurrentBalances</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/MarginAccountCurrentBalances} obj Optional instance to populate.
    * @return {module:model/MarginAccountCurrentBalances} The populated <code>MarginAccountCurrentBalances</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MarginAccountCurrentBalances();
                        
            
            if (data.hasOwnProperty('schema')) {
                obj['schema'] = MarginAccountBalances.constructFromObject(data['schema']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/MarginAccountBalances} schema
    */
    'schema' = undefined;




}
