/**
 * TD Ameritrade API - OAuth2
 * This is replication of the TD Ameritrade API.
 *
 * OpenAPI spec version: 0.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The MarginAccountInitialBalances model module.
* @module model/MarginAccountInitialBalances
* @version 0.1.4
*/
export default class MarginAccountInitialBalances {
    /**
    * Constructs a new <code>MarginAccountInitialBalances</code>.
    * @alias module:model/MarginAccountInitialBalances
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>MarginAccountInitialBalances</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/MarginAccountInitialBalances} obj Optional instance to populate.
    * @return {module:model/MarginAccountInitialBalances} The populated <code>MarginAccountInitialBalances</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MarginAccountInitialBalances();
                        
            
            if (data.hasOwnProperty('accruedInterest')) {
                obj['accruedInterest'] = ApiClient.convertToType(data['accruedInterest'], 'Number');
            }
            if (data.hasOwnProperty('availableFundsNonMarginableTrade')) {
                obj['availableFundsNonMarginableTrade'] = ApiClient.convertToType(data['availableFundsNonMarginableTrade'], 'Number');
            }
            if (data.hasOwnProperty('bondValue')) {
                obj['bondValue'] = ApiClient.convertToType(data['bondValue'], 'Number');
            }
            if (data.hasOwnProperty('buyingPower')) {
                obj['buyingPower'] = ApiClient.convertToType(data['buyingPower'], 'Number');
            }
            if (data.hasOwnProperty('cashBalance')) {
                obj['cashBalance'] = ApiClient.convertToType(data['cashBalance'], 'Number');
            }
            if (data.hasOwnProperty('cashAvailableForTrading')) {
                obj['cashAvailableForTrading'] = ApiClient.convertToType(data['cashAvailableForTrading'], 'Number');
            }
            if (data.hasOwnProperty('cashReceipts')) {
                obj['cashReceipts'] = ApiClient.convertToType(data['cashReceipts'], 'Number');
            }
            if (data.hasOwnProperty('dayTradingBuyingPower')) {
                obj['dayTradingBuyingPower'] = ApiClient.convertToType(data['dayTradingBuyingPower'], 'Number');
            }
            if (data.hasOwnProperty('dayTradingBuyingPowerCall')) {
                obj['dayTradingBuyingPowerCall'] = ApiClient.convertToType(data['dayTradingBuyingPowerCall'], 'Number');
            }
            if (data.hasOwnProperty('dayTradingEquityCall')) {
                obj['dayTradingEquityCall'] = ApiClient.convertToType(data['dayTradingEquityCall'], 'Number');
            }
            if (data.hasOwnProperty('equity')) {
                obj['equity'] = ApiClient.convertToType(data['equity'], 'Number');
            }
            if (data.hasOwnProperty('equityPercentage')) {
                obj['equityPercentage'] = ApiClient.convertToType(data['equityPercentage'], 'Number');
            }
            if (data.hasOwnProperty('liquidationValue')) {
                obj['liquidationValue'] = ApiClient.convertToType(data['liquidationValue'], 'Number');
            }
            if (data.hasOwnProperty('longMarginValue')) {
                obj['longMarginValue'] = ApiClient.convertToType(data['longMarginValue'], 'Number');
            }
            if (data.hasOwnProperty('longOptionMarketValue')) {
                obj['longOptionMarketValue'] = ApiClient.convertToType(data['longOptionMarketValue'], 'Number');
            }
            if (data.hasOwnProperty('longStockValue')) {
                obj['longStockValue'] = ApiClient.convertToType(data['longStockValue'], 'Number');
            }
            if (data.hasOwnProperty('maintenanceCall')) {
                obj['maintenanceCall'] = ApiClient.convertToType(data['maintenanceCall'], 'Number');
            }
            if (data.hasOwnProperty('maintenanceRequirement')) {
                obj['maintenanceRequirement'] = ApiClient.convertToType(data['maintenanceRequirement'], 'Number');
            }
            if (data.hasOwnProperty('margin')) {
                obj['margin'] = ApiClient.convertToType(data['margin'], 'Number');
            }
            if (data.hasOwnProperty('marginEquity')) {
                obj['marginEquity'] = ApiClient.convertToType(data['marginEquity'], 'Number');
            }
            if (data.hasOwnProperty('moneyMarketFund')) {
                obj['moneyMarketFund'] = ApiClient.convertToType(data['moneyMarketFund'], 'Number');
            }
            if (data.hasOwnProperty('mutualFundValue')) {
                obj['mutualFundValue'] = ApiClient.convertToType(data['mutualFundValue'], 'Number');
            }
            if (data.hasOwnProperty('regTCall')) {
                obj['regTCall'] = ApiClient.convertToType(data['regTCall'], 'Number');
            }
            if (data.hasOwnProperty('shortMarginValue')) {
                obj['shortMarginValue'] = ApiClient.convertToType(data['shortMarginValue'], 'Number');
            }
            if (data.hasOwnProperty('shortOptionMarketValue')) {
                obj['shortOptionMarketValue'] = ApiClient.convertToType(data['shortOptionMarketValue'], 'Number');
            }
            if (data.hasOwnProperty('shortStockValue')) {
                obj['shortStockValue'] = ApiClient.convertToType(data['shortStockValue'], 'Number');
            }
            if (data.hasOwnProperty('totalCash')) {
                obj['totalCash'] = ApiClient.convertToType(data['totalCash'], 'Number');
            }
            if (data.hasOwnProperty('isInCall')) {
                obj['isInCall'] = ApiClient.convertToType(data['isInCall'], 'Boolean');
            }
            if (data.hasOwnProperty('unsettledCash')) {
                obj['unsettledCash'] = ApiClient.convertToType(data['unsettledCash'], 'Number');
            }
            if (data.hasOwnProperty('pendingDeposits')) {
                obj['pendingDeposits'] = ApiClient.convertToType(data['pendingDeposits'], 'Number');
            }
            if (data.hasOwnProperty('marginBalance')) {
                obj['marginBalance'] = ApiClient.convertToType(data['marginBalance'], 'Number');
            }
            if (data.hasOwnProperty('shortBalance')) {
                obj['shortBalance'] = ApiClient.convertToType(data['shortBalance'], 'Number');
            }
            if (data.hasOwnProperty('accountValue')) {
                obj['accountValue'] = ApiClient.convertToType(data['accountValue'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {Number} accruedInterest
    */
    'accruedInterest' = undefined;
    /**
    * @member {Number} availableFundsNonMarginableTrade
    */
    'availableFundsNonMarginableTrade' = undefined;
    /**
    * @member {Number} bondValue
    */
    'bondValue' = undefined;
    /**
    * @member {Number} buyingPower
    */
    'buyingPower' = undefined;
    /**
    * @member {Number} cashBalance
    */
    'cashBalance' = undefined;
    /**
    * @member {Number} cashAvailableForTrading
    */
    'cashAvailableForTrading' = undefined;
    /**
    * @member {Number} cashReceipts
    */
    'cashReceipts' = undefined;
    /**
    * @member {Number} dayTradingBuyingPower
    */
    'dayTradingBuyingPower' = undefined;
    /**
    * @member {Number} dayTradingBuyingPowerCall
    */
    'dayTradingBuyingPowerCall' = undefined;
    /**
    * @member {Number} dayTradingEquityCall
    */
    'dayTradingEquityCall' = undefined;
    /**
    * @member {Number} equity
    */
    'equity' = undefined;
    /**
    * @member {Number} equityPercentage
    */
    'equityPercentage' = undefined;
    /**
    * @member {Number} liquidationValue
    */
    'liquidationValue' = undefined;
    /**
    * @member {Number} longMarginValue
    */
    'longMarginValue' = undefined;
    /**
    * @member {Number} longOptionMarketValue
    */
    'longOptionMarketValue' = undefined;
    /**
    * @member {Number} longStockValue
    */
    'longStockValue' = undefined;
    /**
    * @member {Number} maintenanceCall
    */
    'maintenanceCall' = undefined;
    /**
    * @member {Number} maintenanceRequirement
    */
    'maintenanceRequirement' = undefined;
    /**
    * @member {Number} margin
    */
    'margin' = undefined;
    /**
    * @member {Number} marginEquity
    */
    'marginEquity' = undefined;
    /**
    * @member {Number} moneyMarketFund
    */
    'moneyMarketFund' = undefined;
    /**
    * @member {Number} mutualFundValue
    */
    'mutualFundValue' = undefined;
    /**
    * @member {Number} regTCall
    */
    'regTCall' = undefined;
    /**
    * @member {Number} shortMarginValue
    */
    'shortMarginValue' = undefined;
    /**
    * @member {Number} shortOptionMarketValue
    */
    'shortOptionMarketValue' = undefined;
    /**
    * @member {Number} shortStockValue
    */
    'shortStockValue' = undefined;
    /**
    * @member {Number} totalCash
    */
    'totalCash' = undefined;
    /**
    * @member {Boolean} isInCall
    * @default false
    */
    'isInCall' = false;
    /**
    * @member {Number} unsettledCash
    */
    'unsettledCash' = undefined;
    /**
    * @member {Number} pendingDeposits
    */
    'pendingDeposits' = undefined;
    /**
    * @member {Number} marginBalance
    */
    'marginBalance' = undefined;
    /**
    * @member {Number} shortBalance
    */
    'shortBalance' = undefined;
    /**
    * @member {Number} accountValue
    */
    'accountValue' = undefined;




}
