/**
 * TD Ameritrade API - OAuth2
 * This is replication of the TD Ameritrade API.
 *
 * OpenAPI spec version: 0.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The Mover model module.
* @module model/Mover
* @version 0.1.4
*/
export default class Mover {
    /**
    * Constructs a new <code>Mover</code>.
    * @alias module:model/Mover
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>Mover</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Mover} obj Optional instance to populate.
    * @return {module:model/Mover} The populated <code>Mover</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Mover();
                        
            
            if (data.hasOwnProperty('change')) {
                obj['change'] = ApiClient.convertToType(data['change'], 'Number');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('direction')) {
                obj['direction'] = ApiClient.convertToType(data['direction'], 'String');
            }
            if (data.hasOwnProperty('last')) {
                obj['last'] = ApiClient.convertToType(data['last'], 'Number');
            }
            if (data.hasOwnProperty('symbol')) {
                obj['symbol'] = ApiClient.convertToType(data['symbol'], 'String');
            }
            if (data.hasOwnProperty('totalVolume')) {
                obj['totalVolume'] = ApiClient.convertToType(data['totalVolume'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {Number} change
    */
    'change' = undefined;
    /**
    * @member {String} description
    */
    'description' = undefined;
    /**
    * @member {module:model/Mover.DirectionEnum} direction
    */
    'direction' = undefined;
    /**
    * @member {Number} last
    */
    'last' = undefined;
    /**
    * @member {String} symbol
    */
    'symbol' = undefined;
    /**
    * @member {Number} totalVolume
    */
    'totalVolume' = undefined;



    /**
    * Allowed values for the <code>direction</code> property.
    * @enum {String}
    * @readonly
    */
    static DirectionEnum = {
        /**
         * value: "up"
         * @const
         */
        "up": "up",
        /**
         * value: "down"
         * @const
         */
        "down": "down"    };

}
