/**
 * TD Ameritrade API - OAuth2
 * This is replication of the TD Ameritrade API.
 *
 * OpenAPI spec version: 0.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import OptionDeliverableInnerAssetType from './OptionDeliverableInnerAssetType';

/**
* The OptionDeliverableInner model module.
* @module model/OptionDeliverableInner
* @version 0.1.4
*/
export default class OptionDeliverableInner {
    /**
    * Constructs a new <code>OptionDeliverableInner</code>.
    * @alias module:model/OptionDeliverableInner
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>OptionDeliverableInner</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/OptionDeliverableInner} obj Optional instance to populate.
    * @return {module:model/OptionDeliverableInner} The populated <code>OptionDeliverableInner</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OptionDeliverableInner();
                        
            
            if (data.hasOwnProperty('symbol')) {
                obj['symbol'] = ApiClient.convertToType(data['symbol'], 'String');
            }
            if (data.hasOwnProperty('deliverableUnits')) {
                obj['deliverableUnits'] = ApiClient.convertToType(data['deliverableUnits'], 'Number');
            }
            if (data.hasOwnProperty('currencyType')) {
                obj['currencyType'] = ApiClient.convertToType(data['currencyType'], 'String');
            }
            if (data.hasOwnProperty('assetType')) {
                obj['assetType'] = OptionDeliverableInnerAssetType.constructFromObject(data['assetType']);
            }
        }
        return obj;
    }

    /**
    * @member {String} symbol
    */
    'symbol' = undefined;
    /**
    * @member {Number} deliverableUnits
    */
    'deliverableUnits' = undefined;
    /**
    * @member {module:model/OptionDeliverableInner.CurrencyTypeEnum} currencyType
    */
    'currencyType' = undefined;
    /**
    * @member {module:model/OptionDeliverableInnerAssetType} assetType
    */
    'assetType' = undefined;



    /**
    * Allowed values for the <code>currencyType</code> property.
    * @enum {String}
    * @readonly
    */
    static CurrencyTypeEnum = {
        /**
         * value: "USD"
         * @const
         */
        "USD": "USD",
        /**
         * value: "CAD"
         * @const
         */
        "CAD": "CAD",
        /**
         * value: "EUR"
         * @const
         */
        "EUR": "EUR",
        /**
         * value: "JPY"
         * @const
         */
        "JPY": "JPY"    };

}
