/**
 * TD Ameritrade API - OAuth2
 * This is replication of the TD Ameritrade API.
 *
 * OpenAPI spec version: 0.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The OptionChain model module.
* @module model/OptionChain
* @version 0.1.4
*/
export default class OptionChain {
    /**
    * Constructs a new <code>OptionChain</code>.
    * @alias module:model/OptionChain
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>OptionChain</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/OptionChain} obj Optional instance to populate.
    * @return {module:model/OptionChain} The populated <code>OptionChain</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OptionChain();
                        
            
            if (data.hasOwnProperty('symbol')) {
                obj['symbol'] = ApiClient.convertToType(data['symbol'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} symbol
    */
    'symbol' = undefined;
    /**
    * @member {String} status
    */
    'status' = undefined;




}
