/**
 * TD Ameritrade API - OAuth2
 * This is replication of the TD Ameritrade API.
 *
 * OpenAPI spec version: 0.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The OrderGetCancelTime model module.
* @module model/OrderGetCancelTime
* @version 0.1.4
*/
export default class OrderGetCancelTime {
    /**
    * Constructs a new <code>OrderGetCancelTime</code>.
    * @alias module:model/OrderGetCancelTime
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>OrderGetCancelTime</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/OrderGetCancelTime} obj Optional instance to populate.
    * @return {module:model/OrderGetCancelTime} The populated <code>OrderGetCancelTime</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OrderGetCancelTime();
                        
            
            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'String');
            }
            if (data.hasOwnProperty('shortFormat')) {
                obj['shortFormat'] = ApiClient.convertToType(data['shortFormat'], 'Boolean');
            }
        }
        return obj;
    }

    /**
    * @member {String} date
    */
    'date' = undefined;
    /**
    * @member {Boolean} shortFormat
    * @default false
    */
    'shortFormat' = false;




}
