/**
 * TD Ameritrade API - OAuth2
 * This is replication of the TD Ameritrade API.
 *
 * OpenAPI spec version: 0.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import OrderType from './OrderType';

/**
* The OrderGetOrderType model module.
* @module model/OrderGetOrderType
* @version 0.1.4
*/
export default class OrderGetOrderType {
    /**
    * Constructs a new <code>OrderGetOrderType</code>.
    * @alias module:model/OrderGetOrderType
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>OrderGetOrderType</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/OrderGetOrderType} obj Optional instance to populate.
    * @return {module:model/OrderGetOrderType} The populated <code>OrderGetOrderType</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OrderGetOrderType();
                        
            
            if (data.hasOwnProperty('schema')) {
                obj['schema'] = OrderType.constructFromObject(data['schema']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/OrderType} schema
    */
    'schema' = undefined;




}
