/**
 * TD Ameritrade API - OAuth2
 * This is replication of the TD Ameritrade API.
 *
 * OpenAPI spec version: 0.1.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class PeriodType.
* @enum {}
* @readonly
*/
export default class PeriodType {
        /**
         * value: "day"
         * @const
         */
        day = "day";

        /**
         * value: "month"
         * @const
         */
        month = "month";

        /**
         * value: "year"
         * @const
         */
        year = "year";

        /**
         * value: "ytd"
         * @const
         */
        ytd = "ytd";


    /**
    * Returns a <code>PeriodType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/PeriodType} The enum <code>PeriodType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}
