/**
 * TD Ameritrade API - OAuth2
 * This is replication of the TD Ameritrade API.
 *
 * OpenAPI spec version: 0.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The Underlying model module.
* @module model/Underlying
* @version 0.1.4
*/
export default class Underlying {
    /**
    * Constructs a new <code>Underlying</code>.
    * @alias module:model/Underlying
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>Underlying</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Underlying} obj Optional instance to populate.
    * @return {module:model/Underlying} The populated <code>Underlying</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Underlying();
                        
            
            if (data.hasOwnProperty('ask')) {
                obj['ask'] = ApiClient.convertToType(data['ask'], 'Number');
            }
            if (data.hasOwnProperty('askSize')) {
                obj['askSize'] = ApiClient.convertToType(data['askSize'], 'Number');
            }
            if (data.hasOwnProperty('bid')) {
                obj['bid'] = ApiClient.convertToType(data['bid'], 'Number');
            }
            if (data.hasOwnProperty('bidSize')) {
                obj['bidSize'] = ApiClient.convertToType(data['bidSize'], 'Number');
            }
            if (data.hasOwnProperty('change')) {
                obj['change'] = ApiClient.convertToType(data['change'], 'Number');
            }
            if (data.hasOwnProperty('close')) {
                obj['close'] = ApiClient.convertToType(data['close'], 'Number');
            }
            if (data.hasOwnProperty('delayed')) {
                obj['delayed'] = ApiClient.convertToType(data['delayed'], 'Boolean');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('exchangeName')) {
                obj['exchangeName'] = ApiClient.convertToType(data['exchangeName'], 'String');
            }
            if (data.hasOwnProperty('fiftyTwoWeekHigh')) {
                obj['fiftyTwoWeekHigh'] = ApiClient.convertToType(data['fiftyTwoWeekHigh'], 'Number');
            }
            if (data.hasOwnProperty('fiftyTwoWeekLow')) {
                obj['fiftyTwoWeekLow'] = ApiClient.convertToType(data['fiftyTwoWeekLow'], 'Number');
            }
            if (data.hasOwnProperty('highePrice')) {
                obj['highePrice'] = ApiClient.convertToType(data['highePrice'], 'Number');
            }
            if (data.hasOwnProperty('last')) {
                obj['last'] = ApiClient.convertToType(data['last'], 'Number');
            }
            if (data.hasOwnProperty('lowPrice')) {
                obj['lowPrice'] = ApiClient.convertToType(data['lowPrice'], 'Number');
            }
            if (data.hasOwnProperty('mark')) {
                obj['mark'] = ApiClient.convertToType(data['mark'], 'Number');
            }
            if (data.hasOwnProperty('markChange')) {
                obj['markChange'] = ApiClient.convertToType(data['markChange'], 'Number');
            }
            if (data.hasOwnProperty('makrPercentChange')) {
                obj['makrPercentChange'] = ApiClient.convertToType(data['makrPercentChange'], 'Number');
            }
            if (data.hasOwnProperty('openPrice')) {
                obj['openPrice'] = ApiClient.convertToType(data['openPrice'], 'Number');
            }
            if (data.hasOwnProperty('percentChange')) {
                obj['percentChange'] = ApiClient.convertToType(data['percentChange'], 'Number');
            }
            if (data.hasOwnProperty('quoteTime')) {
                obj['quoteTime'] = ApiClient.convertToType(data['quoteTime'], 'Number');
            }
            if (data.hasOwnProperty('symbol')) {
                obj['symbol'] = ApiClient.convertToType(data['symbol'], 'String');
            }
            if (data.hasOwnProperty('totalVolume')) {
                obj['totalVolume'] = ApiClient.convertToType(data['totalVolume'], 'Number');
            }
            if (data.hasOwnProperty('tradeTime')) {
                obj['tradeTime'] = ApiClient.convertToType(data['tradeTime'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {Number} ask
    */
    'ask' = undefined;
    /**
    * @member {Number} askSize
    */
    'askSize' = undefined;
    /**
    * @member {Number} bid
    */
    'bid' = undefined;
    /**
    * @member {Number} bidSize
    */
    'bidSize' = undefined;
    /**
    * @member {Number} change
    */
    'change' = undefined;
    /**
    * @member {Number} close
    */
    'close' = undefined;
    /**
    * @member {Boolean} delayed
    */
    'delayed' = undefined;
    /**
    * @member {String} description
    */
    'description' = undefined;
    /**
    * @member {module:model/Underlying.ExchangeNameEnum} exchangeName
    */
    'exchangeName' = undefined;
    /**
    * @member {Number} fiftyTwoWeekHigh
    */
    'fiftyTwoWeekHigh' = undefined;
    /**
    * @member {Number} fiftyTwoWeekLow
    */
    'fiftyTwoWeekLow' = undefined;
    /**
    * @member {Number} highePrice
    */
    'highePrice' = undefined;
    /**
    * @member {Number} last
    */
    'last' = undefined;
    /**
    * @member {Number} lowPrice
    */
    'lowPrice' = undefined;
    /**
    * @member {Number} mark
    */
    'mark' = undefined;
    /**
    * @member {Number} markChange
    */
    'markChange' = undefined;
    /**
    * @member {Number} makrPercentChange
    */
    'makrPercentChange' = undefined;
    /**
    * @member {Number} openPrice
    */
    'openPrice' = undefined;
    /**
    * @member {Number} percentChange
    */
    'percentChange' = undefined;
    /**
    * @member {Number} quoteTime
    */
    'quoteTime' = undefined;
    /**
    * @member {String} symbol
    */
    'symbol' = undefined;
    /**
    * @member {Number} totalVolume
    */
    'totalVolume' = undefined;
    /**
    * @member {Number} tradeTime
    */
    'tradeTime' = undefined;



    /**
    * Allowed values for the <code>exchangeName</code> property.
    * @enum {String}
    * @readonly
    */
    static ExchangeNameEnum = {
        /**
         * value: "IND"
         * @const
         */
        "IND": "IND",
        /**
         * value: "ASE"
         * @const
         */
        "ASE": "ASE",
        /**
         * value: "NYS"
         * @const
         */
        "NYS": "NYS",
        /**
         * value: "NAS"
         * @const
         */
        "NAS": "NAS",
        /**
         * value: "NAP"
         * @const
         */
        "NAP": "NAP",
        /**
         * value: "PAC"
         * @const
         */
        "PAC": "PAC",
        /**
         * value: "OPR"
         * @const
         */
        "OPR": "OPR",
        /**
         * value: "BATS"
         * @const
         */
        "BATS": "BATS"    };

}
