/**
 * TD Ameritrade API - OAuth2
 * This is replication of the TD Ameritrade API.
 *
 * OpenAPI spec version: 0.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import LotMethod from './LotMethod';

/**
* The UserPrincipalPreferencesMutualFundTaxLotMethod model module.
* @module model/UserPrincipalPreferencesMutualFundTaxLotMethod
* @version 0.1.4
*/
export default class UserPrincipalPreferencesMutualFundTaxLotMethod {
    /**
    * Constructs a new <code>UserPrincipalPreferencesMutualFundTaxLotMethod</code>.
    * @alias module:model/UserPrincipalPreferencesMutualFundTaxLotMethod
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>UserPrincipalPreferencesMutualFundTaxLotMethod</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/UserPrincipalPreferencesMutualFundTaxLotMethod} obj Optional instance to populate.
    * @return {module:model/UserPrincipalPreferencesMutualFundTaxLotMethod} The populated <code>UserPrincipalPreferencesMutualFundTaxLotMethod</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserPrincipalPreferencesMutualFundTaxLotMethod();
                        
            
            if (data.hasOwnProperty('schema')) {
                obj['schema'] = LotMethod.constructFromObject(data['schema']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/LotMethod} schema
    */
    'schema' = undefined;




}
