/**
 * TD Ameritrade API - OAuth2
 * This is replication of the TD Ameritrade API.
 *
 * OpenAPI spec version: 0.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import WatchListInstrument from './WatchListInstrument';

/**
* The WatchListWatchlistItems model module.
* @module model/WatchListWatchlistItems
* @version 0.1.4
*/
export default class WatchListWatchlistItems {
    /**
    * Constructs a new <code>WatchListWatchlistItems</code>.
    * @alias module:model/WatchListWatchlistItems
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>WatchListWatchlistItems</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/WatchListWatchlistItems} obj Optional instance to populate.
    * @return {module:model/WatchListWatchlistItems} The populated <code>WatchListWatchlistItems</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WatchListWatchlistItems();
                        
            
            if (data.hasOwnProperty('sequenceId')) {
                obj['sequenceId'] = ApiClient.convertToType(data['sequenceId'], 'Number');
            }
            if (data.hasOwnProperty('quantity')) {
                obj['quantity'] = ApiClient.convertToType(data['quantity'], 'Number');
            }
            if (data.hasOwnProperty('averagePrice')) {
                obj['averagePrice'] = ApiClient.convertToType(data['averagePrice'], 'Number');
            }
            if (data.hasOwnProperty('commission')) {
                obj['commission'] = ApiClient.convertToType(data['commission'], 'Number');
            }
            if (data.hasOwnProperty('purchasedDate')) {
                obj['purchasedDate'] = ApiClient.convertToType(data['purchasedDate'], Object);
            }
            if (data.hasOwnProperty('instrument')) {
                obj['instrument'] = WatchListInstrument.constructFromObject(data['instrument']);
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {Number} sequenceId
    */
    'sequenceId' = undefined;
    /**
    * @member {Number} quantity
    */
    'quantity' = undefined;
    /**
    * @member {Number} averagePrice
    */
    'averagePrice' = undefined;
    /**
    * @member {Number} commission
    */
    'commission' = undefined;
    /**
    * @member {Object} purchasedDate
    */
    'purchasedDate' = undefined;
    /**
    * @member {module:model/WatchListInstrument} instrument
    */
    'instrument' = undefined;
    /**
    * @member {module:model/WatchListWatchlistItems.StatusEnum} status
    */
    'status' = undefined;



    /**
    * Allowed values for the <code>status</code> property.
    * @enum {String}
    * @readonly
    */
    static StatusEnum = {
        /**
         * value: "UNCHANGED"
         * @const
         */
        "UNCHANGED": "UNCHANGED",
        /**
         * value: "CREATED"
         * @const
         */
        "CREATED": "CREATED",
        /**
         * value: "UPDATED"
         * @const
         */
        "UPDATED": "UPDATED",
        /**
         * value: "DELETED"
         * @const
         */
        "DELETED": "DELETED"    };

}
