/**
 * TD Ameritrade API - OAuth2
 * This is replication of the TD Ameritrade API.
 *
 * OpenAPI spec version: 0.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import WatchListRequestInstrument from './WatchListRequestInstrument';

/**
* The WatchListRequestWatchlistItems model module.
* @module model/WatchListRequestWatchlistItems
* @version 0.1.4
*/
export default class WatchListRequestWatchlistItems {
    /**
    * Constructs a new <code>WatchListRequestWatchlistItems</code>.
    * @alias module:model/WatchListRequestWatchlistItems
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>WatchListRequestWatchlistItems</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/WatchListRequestWatchlistItems} obj Optional instance to populate.
    * @return {module:model/WatchListRequestWatchlistItems} The populated <code>WatchListRequestWatchlistItems</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WatchListRequestWatchlistItems();
                        
            
            if (data.hasOwnProperty('quantity')) {
                obj['quantity'] = ApiClient.convertToType(data['quantity'], 'Number');
            }
            if (data.hasOwnProperty('averagePrice')) {
                obj['averagePrice'] = ApiClient.convertToType(data['averagePrice'], 'Number');
            }
            if (data.hasOwnProperty('commission')) {
                obj['commission'] = ApiClient.convertToType(data['commission'], 'Number');
            }
            if (data.hasOwnProperty('purchasedDate')) {
                obj['purchasedDate'] = ApiClient.convertToType(data['purchasedDate'], Object);
            }
            if (data.hasOwnProperty('instrument')) {
                obj['instrument'] = WatchListRequestInstrument.constructFromObject(data['instrument']);
            }
            if (data.hasOwnProperty('sequenceId')) {
                obj['sequenceId'] = ApiClient.convertToType(data['sequenceId'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {Number} quantity
    */
    'quantity' = undefined;
    /**
    * @member {Number} averagePrice
    */
    'averagePrice' = undefined;
    /**
    * @member {Number} commission
    */
    'commission' = undefined;
    /**
    * @member {Object} purchasedDate
    */
    'purchasedDate' = undefined;
    /**
    * @member {module:model/WatchListRequestInstrument} instrument
    */
    'instrument' = undefined;
    /**
    * @member {Number} sequenceId
    */
    'sequenceId' = undefined;




}
