/**
 * TD Ameritrade API - OAuth2
 * This is replication of the TD Ameritrade API.
 *
 * OpenAPI spec version: 0.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import WatchListRequestWatchlistItems from './WatchListRequestWatchlistItems';

/**
* The WatchListRequest model module.
* @module model/WatchListRequest
* @version 0.1.4
*/
export default class WatchListRequest {
    /**
    * Constructs a new <code>WatchListRequest</code>.
    * @alias module:model/WatchListRequest
    * @class
    * @param name {String} 
    * @param watchlistItems {Array.<module:model/WatchListRequestWatchlistItems>} 
    */

    constructor(name, watchlistItems) {
        
        
        this['name'] = name;
        this['watchlistItems'] = watchlistItems;
        
    }

    /**
    * Constructs a <code>WatchListRequest</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/WatchListRequest} obj Optional instance to populate.
    * @return {module:model/WatchListRequest} The populated <code>WatchListRequest</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WatchListRequest();
                        
            
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('watchlistId')) {
                obj['watchlistId'] = ApiClient.convertToType(data['watchlistId'], 'String');
            }
            if (data.hasOwnProperty('watchlistItems')) {
                obj['watchlistItems'] = ApiClient.convertToType(data['watchlistItems'], [WatchListRequestWatchlistItems]);
            }
        }
        return obj;
    }

    /**
    * @member {String} name
    */
    'name' = undefined;
    /**
    * @member {String} watchlistId
    */
    'watchlistId' = undefined;
    /**
    * @member {Array.<module:model/WatchListRequestWatchlistItems>} watchlistItems
    */
    'watchlistItems' = undefined;




}
