/*
 * TD Ameritrade API - OAuth2
 * This is replication of the TD Ameritrade API.
 *
 * OpenAPI spec version: 0.1.4
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.14
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/EquityAssetType'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./EquityAssetType'));
  } else {
    // Browser globals (root is window)
    if (!root.GitChrisQueen_TDA_JS) {
      root.GitChrisQueen_TDA_JS = {};
    }
    root.GitChrisQueen_TDA_JS.MutualFund = factory(root.GitChrisQueen_TDA_JS.ApiClient, root.GitChrisQueen_TDA_JS.EquityAssetType);
  }
}(this, function(ApiClient, EquityAssetType) {
  'use strict';

  /**
   * The MutualFund model module.
   * @module model/MutualFund
   * @version 0.1.4
   */

  /**
   * Constructs a new <code>MutualFund</code>.
   * @alias module:model/MutualFund
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>MutualFund</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MutualFund} obj Optional instance to populate.
   * @return {module:model/MutualFund} The populated <code>MutualFund</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('assetType'))
        obj.assetType = EquityAssetType.constructFromObject(data['assetType']);
      if (data.hasOwnProperty('cusip'))
        obj.cusip = ApiClient.convertToType(data['cusip'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('symbol'))
        obj.symbol = ApiClient.convertToType(data['symbol'], 'String');
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
    }
    return obj;
  }

  /**
   * @member {module:model/EquityAssetType} assetType
   */
  exports.prototype.assetType = undefined;

  /**
   * @member {String} cusip
   */
  exports.prototype.cusip = undefined;

  /**
   * @member {String} description
   */
  exports.prototype.description = undefined;

  /**
   * @member {String} symbol
   */
  exports.prototype.symbol = undefined;

  /**
   * @member {module:model/MutualFund.TypeEnum} type
   */
  exports.prototype.type = undefined;


  /**
   * Allowed values for the <code>type</code> property.
   * @enum {String}
   * @readonly
   */
  exports.TypeEnum = {
    /**
     * value: "NOT_APPLICABLE"
     * @const
     */
    NOT_APPLICABLE: "NOT_APPLICABLE",

    /**
     * value: "OPEN_END_NON_TAXABLE"
     * @const
     */
    OPEN_END_NON_TAXABLE: "OPEN_END_NON_TAXABLE",

    /**
     * value: "OPEN_END_TAXABLE"
     * @const
     */
    OPEN_END_TAXABLE: "OPEN_END_TAXABLE",

    /**
     * value: "NO_LOAD_NON_TAXABLE"
     * @const
     */
    NO_LOAD_NON_TAXABLE: "NO_LOAD_NON_TAXABLE",

    /**
     * value: "NO_LOAD_TAXABLE"
     * @const
     */
    NO_LOAD_TAXABLE: "NO_LOAD_TAXABLE"
  };

  return exports;

}));
