/*
 * TD Ameritrade API - OAuth2
 * This is replication of the TD Ameritrade API.
 *
 * OpenAPI spec version: 0.1.4
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.14
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/EquityAssetType', 'model/OptionOptionDeliverables'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./EquityAssetType'), require('./OptionOptionDeliverables'));
  } else {
    // Browser globals (root is window)
    if (!root.GitChrisQueen_TDA_JS) {
      root.GitChrisQueen_TDA_JS = {};
    }
    root.GitChrisQueen_TDA_JS.Option = factory(root.GitChrisQueen_TDA_JS.ApiClient, root.GitChrisQueen_TDA_JS.EquityAssetType, root.GitChrisQueen_TDA_JS.OptionOptionDeliverables);
  }
}(this, function(ApiClient, EquityAssetType, OptionOptionDeliverables) {
  'use strict';

  /**
   * The Option model module.
   * @module model/Option
   * @version 0.1.4
   */

  /**
   * Constructs a new <code>Option</code>.
   * @alias module:model/Option
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>Option</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Option} obj Optional instance to populate.
   * @return {module:model/Option} The populated <code>Option</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('assetType'))
        obj.assetType = EquityAssetType.constructFromObject(data['assetType']);
      if (data.hasOwnProperty('cusip'))
        obj.cusip = ApiClient.convertToType(data['cusip'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('optionDeliverables'))
        obj.optionDeliverables = ApiClient.convertToType(data['optionDeliverables'], [OptionOptionDeliverables]);
      if (data.hasOwnProperty('optionMultiplier'))
        obj.optionMultiplier = ApiClient.convertToType(data['optionMultiplier'], 'Number');
      if (data.hasOwnProperty('putCall'))
        obj.putCall = ApiClient.convertToType(data['putCall'], 'String');
      if (data.hasOwnProperty('symbol'))
        obj.symbol = ApiClient.convertToType(data['symbol'], 'String');
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('underlyingSymbol'))
        obj.underlyingSymbol = ApiClient.convertToType(data['underlyingSymbol'], 'String');
    }
    return obj;
  }

  /**
   * @member {module:model/EquityAssetType} assetType
   */
  exports.prototype.assetType = undefined;

  /**
   * @member {String} cusip
   */
  exports.prototype.cusip = undefined;

  /**
   * @member {String} description
   */
  exports.prototype.description = undefined;

  /**
   * @member {Array.<module:model/OptionOptionDeliverables>} optionDeliverables
   */
  exports.prototype.optionDeliverables = undefined;

  /**
   * @member {Number} optionMultiplier
   */
  exports.prototype.optionMultiplier = undefined;

  /**
   * @member {module:model/Option.PutCallEnum} putCall
   */
  exports.prototype.putCall = undefined;

  /**
   * @member {String} symbol
   */
  exports.prototype.symbol = undefined;

  /**
   * @member {module:model/Option.TypeEnum} type
   */
  exports.prototype.type = undefined;

  /**
   * @member {String} underlyingSymbol
   */
  exports.prototype.underlyingSymbol = undefined;


  /**
   * Allowed values for the <code>putCall</code> property.
   * @enum {String}
   * @readonly
   */
  exports.PutCallEnum = {
    /**
     * value: "PUT"
     * @const
     */
    PUT: "PUT",

    /**
     * value: "CALL"
     * @const
     */
    CALL: "CALL"
  };


  /**
   * Allowed values for the <code>type</code> property.
   * @enum {String}
   * @readonly
   */
  exports.TypeEnum = {
    /**
     * value: "VANILLA"
     * @const
     */
    VANILLA: "VANILLA",

    /**
     * value: "BINARY"
     * @const
     */
    BINARY: "BINARY",

    /**
     * value: "BARRIER"
     * @const
     */
    BARRIER: "BARRIER"
  };

  return exports;

}));
