/*
 * TD Ameritrade API - OAuth2
 * This is replication of the TD Ameritrade API.
 *
 * OpenAPI spec version: 0.1.4
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.14
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.GitChrisQueen_TDA_JS) {
      root.GitChrisQueen_TDA_JS = {};
    }
    root.GitChrisQueen_TDA_JS.OrderType = factory(root.GitChrisQueen_TDA_JS.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * Enum class OrderType.
   * @enum {String}
   * @readonly
   */
  var exports = {
    /**
     * value: "MARKET"
     * @const
     */
    MARKET: "MARKET",

    /**
     * value: "LIMIT"
     * @const
     */
    LIMIT: "LIMIT",

    /**
     * value: "STOP"
     * @const
     */
    STOP: "STOP",

    /**
     * value: "STOP_LIMIT"
     * @const
     */
    STOP_LIMIT: "STOP_LIMIT",

    /**
     * value: "TRAILING_STOP"
     * @const
     */
    TRAILING_STOP: "TRAILING_STOP",

    /**
     * value: "MARKET_ON_CLOSE"
     * @const
     */
    MARKET_ON_CLOSE: "MARKET_ON_CLOSE",

    /**
     * value: "EXERCISE"
     * @const
     */
    EXERCISE: "EXERCISE",

    /**
     * value: "TRAILING_STOP_LIMIT"
     * @const
     */
    TRAILING_STOP_LIMIT: "TRAILING_STOP_LIMIT",

    /**
     * value: "NET_DEBIT"
     * @const
     */
    NET_DEBIT: "NET_DEBIT",

    /**
     * value: "NET_CREDIT"
     * @const
     */
    NET_CREDIT: "NET_CREDIT",

    /**
     * value: "NET_ZERO"
     * @const
     */
    NET_ZERO: "NET_ZERO"
  };

  /**
   * Returns a <code>OrderType</code> enum value from a JavaScript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
   * @return {module:model/OrderType} The enum <code>OrderType</code> value.
   */
  exports.constructFromObject = function(object) {
    return object;
  }

  return exports;
}));
