/*
 * TD Ameritrade API - OAuth2
 * This is replication of the TD Ameritrade API.
 *
 * OpenAPI spec version: 0.1.4
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.14
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.GitChrisQueen_TDA_JS) {
      root.GitChrisQueen_TDA_JS = {};
    }
    root.GitChrisQueen_TDA_JS.WatchListRequestInstrument = factory(root.GitChrisQueen_TDA_JS.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The WatchListRequestInstrument model module.
   * @module model/WatchListRequestInstrument
   * @version 0.1.4
   */

  /**
   * Constructs a new <code>WatchListRequestInstrument</code>.
   * @alias module:model/WatchListRequestInstrument
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>WatchListRequestInstrument</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/WatchListRequestInstrument} obj Optional instance to populate.
   * @return {module:model/WatchListRequestInstrument} The populated <code>WatchListRequestInstrument</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('assetType'))
        obj.assetType = ApiClient.convertToType(data['assetType'], 'String');
      if (data.hasOwnProperty('symbol'))
        obj.symbol = ApiClient.convertToType(data['symbol'], 'String');
    }
    return obj;
  }

  /**
   * @member {module:model/WatchListRequestInstrument.AssetTypeEnum} assetType
   */
  exports.prototype.assetType = undefined;

  /**
   * @member {String} symbol
   */
  exports.prototype.symbol = undefined;


  /**
   * Allowed values for the <code>assetType</code> property.
   * @enum {String}
   * @readonly
   */
  exports.AssetTypeEnum = {
    /**
     * value: "EQUITY"
     * @const
     */
    EQUITY: "EQUITY",

    /**
     * value: "OPTION"
     * @const
     */
    OPTION: "OPTION",

    /**
     * value: "MUTUAL_FUND"
     * @const
     */
    MUTUAL_FUND: "MUTUAL_FUND",

    /**
     * value: "FIXED_INCOME"
     * @const
     */
    FIXED_INCOME: "FIXED_INCOME",

    /**
     * value: "INDEX"
     * @const
     */
    INDEX: "INDEX"
  };

  return exports;

}));
