/**
 * TD Ameritrade API - OAuth2
 * This is replication of the TD Ameritrade API.
 *
 * OpenAPI spec version: 1.0.0-oas3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from "../ApiClient";
import CandleList from '../model/CandleList';

/**
* PriceHistory service.
* @module api/PriceHistoryApi
* @version 1.0.0-oas3
*/
export default class PriceHistoryApi {

    /**
    * Constructs a new PriceHistoryApi. 
    * @alias module:api/PriceHistoryApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Get price history for a symbol
     * @param {Object} opts Optional parameters
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/CandleList} and HTTP response
     */
    marketdataSymbolPricehistoryGETWithHttpInfo(Symbol, PeriodType, opts) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
        'symbol': Symbol
      };
      let queryParams = {
        'apikey': opts['Apikey'],
        'periodType': PeriodType,
        'period': opts['Period'],
        'frequencyType': opts['FrequencyType'],
        'frequency': opts['Frequency'],
        'endDate': opts['EndDate'],
        'startDate': opts['StartDate'],
        'needExtendedHoursData': opts['NeedExtendedHoursData']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = CandleList;

      return this.apiClient.callApi(
        '/marketdata/{symbol}/pricehistory', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Get price history for a symbol
     * @param {Object} opts Optional parameters
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/CandleList}
     */
    marketdataSymbolPricehistoryGET(Symbol, PeriodType, opts) {
      return this.marketdataSymbolPricehistoryGETWithHttpInfo(Symbol, PeriodType, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }

}
