/*
 * TD Ameritrade API - OAuth2
 * This is replication of the TD Ameritrade API.
 *
 * OpenAPI spec version: 1.0.0-oas3
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.14
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.@GitchrisqueenTdameritradeApi);
  }
}(this, function(expect, @GitchrisqueenTdameritradeApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('FrequencyType', function() {
      beforeEach(function() {
        instance = @GitchrisqueenTdameritradeApi.FrequencyType;
      });

      it('should create an instance of FrequencyType', function() {
        // TODO: update the code to test FrequencyType
        expect(instance).to.be.a('object');
      });

      it('should have the property Minute', function() {
        expect(instance).to.have.property('Minute');
        expect(instance.Minute).to.be("minute");
      });

      it('should have the property Daily', function() {
        expect(instance).to.have.property('Daily');
        expect(instance.Daily).to.be("daily");
      });

      it('should have the property Weekly', function() {
        expect(instance).to.have.property('Weekly');
        expect(instance.Weekly).to.be("weekly");
      });

      it('should have the property Monthly', function() {
        expect(instance).to.have.property('Monthly');
        expect(instance.Monthly).to.be("monthly");
      });

    });
  });

}));
