/*
 * TD Ameritrade API - OAuth2
 * This is replication of the TD Ameritrade API.
 *
 * OpenAPI spec version: 1.0.0-oas3
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.14
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.@GitchrisqueenTdameritradeApi);
  }
}(this, function(expect, @GitchrisqueenTdameritradeApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('PeriodType', function() {
      beforeEach(function() {
        instance = @GitchrisqueenTdameritradeApi.PeriodType;
      });

      it('should create an instance of PeriodType', function() {
        // TODO: update the code to test PeriodType
        expect(instance).to.be.a('object');
      });

      it('should have the property Day', function() {
        expect(instance).to.have.property('Day');
        expect(instance.Day).to.be("day");
      });

      it('should have the property Month', function() {
        expect(instance).to.have.property('Month');
        expect(instance.Month).to.be("month");
      });

      it('should have the property Year', function() {
        expect(instance).to.have.property('Year');
        expect(instance.Year).to.be("year");
      });

      it('should have the property Ytd', function() {
        expect(instance).to.have.property('Ytd');
        expect(instance.Ytd).to.be("ytd");
      });

    });
  });

}));
