/**
 * TD Ameritrade API - OAuth2
 * This is replication of the TD Ameritrade API.
 *
 * OpenAPI spec version: 0.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GitChrisQueen_TDA_JS);
  }
}(this, function(expect, GitChrisQueen_TDA_JS) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new GitChrisQueen_TDA_JS.CashAccountInitialBalances();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CashAccountInitialBalances', function() {
    it('should create an instance of CashAccountInitialBalances', function() {
      // uncomment below and update the code to test CashAccountInitialBalances
      //var instane = new GitChrisQueen_TDA_JS.CashAccountInitialBalances();
      //expect(instance).to.be.a(GitChrisQueen_TDA_JS.CashAccountInitialBalances);
    });

    it('should have the property accruedInterest (base name: "accruedInterest")', function() {
      // uncomment below and update the code to test the property accruedInterest
      //var instane = new GitChrisQueen_TDA_JS.CashAccountInitialBalances();
      //expect(instance).to.be();
    });

    it('should have the property cashAvailableForTrading (base name: "cashAvailableForTrading")', function() {
      // uncomment below and update the code to test the property cashAvailableForTrading
      //var instane = new GitChrisQueen_TDA_JS.CashAccountInitialBalances();
      //expect(instance).to.be();
    });

    it('should have the property cashAvailableForWithdrawal (base name: "cashAvailableForWithdrawal")', function() {
      // uncomment below and update the code to test the property cashAvailableForWithdrawal
      //var instane = new GitChrisQueen_TDA_JS.CashAccountInitialBalances();
      //expect(instance).to.be();
    });

    it('should have the property cashBalance (base name: "cashBalance")', function() {
      // uncomment below and update the code to test the property cashBalance
      //var instane = new GitChrisQueen_TDA_JS.CashAccountInitialBalances();
      //expect(instance).to.be();
    });

    it('should have the property bondValue (base name: "bondValue")', function() {
      // uncomment below and update the code to test the property bondValue
      //var instane = new GitChrisQueen_TDA_JS.CashAccountInitialBalances();
      //expect(instance).to.be();
    });

    it('should have the property cashReceipts (base name: "cashReceipts")', function() {
      // uncomment below and update the code to test the property cashReceipts
      //var instane = new GitChrisQueen_TDA_JS.CashAccountInitialBalances();
      //expect(instance).to.be();
    });

    it('should have the property liquidationValue (base name: "liquidationValue")', function() {
      // uncomment below and update the code to test the property liquidationValue
      //var instane = new GitChrisQueen_TDA_JS.CashAccountInitialBalances();
      //expect(instance).to.be();
    });

    it('should have the property longOptionMarketValue (base name: "longOptionMarketValue")', function() {
      // uncomment below and update the code to test the property longOptionMarketValue
      //var instane = new GitChrisQueen_TDA_JS.CashAccountInitialBalances();
      //expect(instance).to.be();
    });

    it('should have the property longStockValue (base name: "longStockValue")', function() {
      // uncomment below and update the code to test the property longStockValue
      //var instane = new GitChrisQueen_TDA_JS.CashAccountInitialBalances();
      //expect(instance).to.be();
    });

    it('should have the property moneyMarketFund (base name: "moneyMarketFund")', function() {
      // uncomment below and update the code to test the property moneyMarketFund
      //var instane = new GitChrisQueen_TDA_JS.CashAccountInitialBalances();
      //expect(instance).to.be();
    });

    it('should have the property mutualFundValue (base name: "mutualFundValue")', function() {
      // uncomment below and update the code to test the property mutualFundValue
      //var instane = new GitChrisQueen_TDA_JS.CashAccountInitialBalances();
      //expect(instance).to.be();
    });

    it('should have the property shortOptionMarketValue (base name: "shortOptionMarketValue")', function() {
      // uncomment below and update the code to test the property shortOptionMarketValue
      //var instane = new GitChrisQueen_TDA_JS.CashAccountInitialBalances();
      //expect(instance).to.be();
    });

    it('should have the property shortStockValue (base name: "shortStockValue")', function() {
      // uncomment below and update the code to test the property shortStockValue
      //var instane = new GitChrisQueen_TDA_JS.CashAccountInitialBalances();
      //expect(instance).to.be();
    });

    it('should have the property isInCall (base name: "isInCall")', function() {
      // uncomment below and update the code to test the property isInCall
      //var instane = new GitChrisQueen_TDA_JS.CashAccountInitialBalances();
      //expect(instance).to.be();
    });

    it('should have the property unsettledCash (base name: "unsettledCash")', function() {
      // uncomment below and update the code to test the property unsettledCash
      //var instane = new GitChrisQueen_TDA_JS.CashAccountInitialBalances();
      //expect(instance).to.be();
    });

    it('should have the property cashDebitCallValue (base name: "cashDebitCallValue")', function() {
      // uncomment below and update the code to test the property cashDebitCallValue
      //var instane = new GitChrisQueen_TDA_JS.CashAccountInitialBalances();
      //expect(instance).to.be();
    });

    it('should have the property pendingDeposits (base name: "pendingDeposits")', function() {
      // uncomment below and update the code to test the property pendingDeposits
      //var instane = new GitChrisQueen_TDA_JS.CashAccountInitialBalances();
      //expect(instance).to.be();
    });

    it('should have the property accountValue (base name: "accountValue")', function() {
      // uncomment below and update the code to test the property accountValue
      //var instane = new GitChrisQueen_TDA_JS.CashAccountInitialBalances();
      //expect(instance).to.be();
    });

  });

}));
