/*
 * TD Ameritrade API - OAuth2
 * This is replication of the TD Ameritrade API.
 *
 * OpenAPI spec version: 0.1.3
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.14
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GitChrisQueen_TDA_JS);
  }
}(this, function(expect, GitChrisQueen_TDA_JS) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('EASObject', function() {
      beforeEach(function() {
        instance = new GitChrisQueen_TDA_JS.EASObject();
      });

      it('should create an instance of EASObject', function() {
        // TODO: update the code to test EASObject
        expect(instance).to.be.a(GitChrisQueen_TDA_JS.EASObject);
      });

      it('should have the property AccessToken (base name: "access_token")', function() {
        // TODO: update the code to test the property AccessToken
        expect(instance).to.have.property('AccessToken');
        // expect(instance.AccessToken).to.be(expectedValueLiteral);
      });

      it('should have the property ExpiresIn (base name: "expires_in")', function() {
        // TODO: update the code to test the property ExpiresIn
        expect(instance).to.have.property('ExpiresIn');
        // expect(instance.ExpiresIn).to.be(expectedValueLiteral);
      });

      it('should have the property RefreshToken (base name: "refresh_token")', function() {
        // TODO: update the code to test the property RefreshToken
        expect(instance).to.have.property('RefreshToken');
        // expect(instance.RefreshToken).to.be(expectedValueLiteral);
      });

      it('should have the property RefreshTokenExpiresIn (base name: "refresh_token_expires_in")', function() {
        // TODO: update the code to test the property RefreshTokenExpiresIn
        expect(instance).to.have.property('RefreshTokenExpiresIn');
        // expect(instance.RefreshTokenExpiresIn).to.be(expectedValueLiteral);
      });

      it('should have the property Scope (base name: "scope")', function() {
        // TODO: update the code to test the property Scope
        expect(instance).to.have.property('Scope');
        // expect(instance.Scope).to.be(expectedValueLiteral);
      });

      it('should have the property TokenType (base name: "token_type")', function() {
        // TODO: update the code to test the property TokenType
        expect(instance).to.have.property('TokenType');
        // expect(instance.TokenType).to.be(expectedValueLiteral);
      });

    });
  });

}));
