/*
 * TD Ameritrade API - OAuth2
 * This is replication of the TD Ameritrade API.
 *
 * OpenAPI spec version: 0.1.4
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.14
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GitChrisQueen_TDA_JS);
  }
}(this, function(expect, GitChrisQueen_TDA_JS) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('ExecutionExecutionLegs', function() {
      beforeEach(function() {
        instance = new GitChrisQueen_TDA_JS.ExecutionExecutionLegs();
      });

      it('should create an instance of ExecutionExecutionLegs', function() {
        // TODO: update the code to test ExecutionExecutionLegs
        expect(instance).to.be.a(GitChrisQueen_TDA_JS.ExecutionExecutionLegs);
      });

      it('should have the property legId (base name: "legId")', function() {
        // TODO: update the code to test the property legId
        expect(instance).to.have.property('legId');
        // expect(instance.legId).to.be(expectedValueLiteral);
      });

      it('should have the property mismarkedQuantity (base name: "mismarkedQuantity")', function() {
        // TODO: update the code to test the property mismarkedQuantity
        expect(instance).to.have.property('mismarkedQuantity');
        // expect(instance.mismarkedQuantity).to.be(expectedValueLiteral);
      });

      it('should have the property price (base name: "price")', function() {
        // TODO: update the code to test the property price
        expect(instance).to.have.property('price');
        // expect(instance.price).to.be(expectedValueLiteral);
      });

      it('should have the property quantity (base name: "quantity")', function() {
        // TODO: update the code to test the property quantity
        expect(instance).to.have.property('quantity');
        // expect(instance.quantity).to.be(expectedValueLiteral);
      });

      it('should have the property time (base name: "time")', function() {
        // TODO: update the code to test the property time
        expect(instance).to.have.property('time');
        // expect(instance.time).to.be(expectedValueLiteral);
      });

    });
  });

}));
