/*
 * TD Ameritrade API - OAuth2
 * This is replication of the TD Ameritrade API.
 *
 * OpenAPI spec version: 0.1.4
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.14
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GitChrisQueen_TDA_JS);
  }
}(this, function(expect, GitChrisQueen_TDA_JS) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('OptionQuote', function() {
      beforeEach(function() {
        instance = new GitChrisQueen_TDA_JS.OptionQuote();
      });

      it('should create an instance of OptionQuote', function() {
        // TODO: update the code to test OptionQuote
        expect(instance).to.be.a(GitChrisQueen_TDA_JS.OptionQuote);
      });

      it('should have the property askPrice (base name: "askPrice")', function() {
        // TODO: update the code to test the property askPrice
        expect(instance).to.have.property('askPrice');
        // expect(instance.askPrice).to.be(expectedValueLiteral);
      });

      it('should have the property askSize (base name: "askSize")', function() {
        // TODO: update the code to test the property askSize
        expect(instance).to.have.property('askSize');
        // expect(instance.askSize).to.be(expectedValueLiteral);
      });

      it('should have the property bidPrice (base name: "bidPrice")', function() {
        // TODO: update the code to test the property bidPrice
        expect(instance).to.have.property('bidPrice');
        // expect(instance.bidPrice).to.be(expectedValueLiteral);
      });

      it('should have the property bidSize (base name: "bidSize")', function() {
        // TODO: update the code to test the property bidSize
        expect(instance).to.have.property('bidSize');
        // expect(instance.bidSize).to.be(expectedValueLiteral);
      });

      it('should have the property closePrice (base name: "closePrice")', function() {
        // TODO: update the code to test the property closePrice
        expect(instance).to.have.property('closePrice');
        // expect(instance.closePrice).to.be(expectedValueLiteral);
      });

      it('should have the property contractType (base name: "contractType")', function() {
        // TODO: update the code to test the property contractType
        expect(instance).to.have.property('contractType');
        // expect(instance.contractType).to.be(expectedValueLiteral);
      });

      it('should have the property deliverables (base name: "deliverables")', function() {
        // TODO: update the code to test the property deliverables
        expect(instance).to.have.property('deliverables');
        // expect(instance.deliverables).to.be(expectedValueLiteral);
      });

      it('should have the property delta (base name: "delta")', function() {
        // TODO: update the code to test the property delta
        expect(instance).to.have.property('delta');
        // expect(instance.delta).to.be(expectedValueLiteral);
      });

      it('should have the property description (base name: "description")', function() {
        // TODO: update the code to test the property description
        expect(instance).to.have.property('description');
        // expect(instance.description).to.be(expectedValueLiteral);
      });

      it('should have the property exchange (base name: "exchange")', function() {
        // TODO: update the code to test the property exchange
        expect(instance).to.have.property('exchange');
        // expect(instance.exchange).to.be(expectedValueLiteral);
      });

      it('should have the property exchangeName (base name: "exchangeName")', function() {
        // TODO: update the code to test the property exchangeName
        expect(instance).to.have.property('exchangeName');
        // expect(instance.exchangeName).to.be(expectedValueLiteral);
      });

      it('should have the property gamma (base name: "gamma")', function() {
        // TODO: update the code to test the property gamma
        expect(instance).to.have.property('gamma');
        // expect(instance.gamma).to.be(expectedValueLiteral);
      });

      it('should have the property highPrice (base name: "highPrice")', function() {
        // TODO: update the code to test the property highPrice
        expect(instance).to.have.property('highPrice');
        // expect(instance.highPrice).to.be(expectedValueLiteral);
      });

      it('should have the property lastPrice (base name: "lastPrice")', function() {
        // TODO: update the code to test the property lastPrice
        expect(instance).to.have.property('lastPrice');
        // expect(instance.lastPrice).to.be(expectedValueLiteral);
      });

      it('should have the property lastSize (base name: "lastSize")', function() {
        // TODO: update the code to test the property lastSize
        expect(instance).to.have.property('lastSize');
        // expect(instance.lastSize).to.be(expectedValueLiteral);
      });

      it('should have the property lowPrice (base name: "lowPrice")', function() {
        // TODO: update the code to test the property lowPrice
        expect(instance).to.have.property('lowPrice');
        // expect(instance.lowPrice).to.be(expectedValueLiteral);
      });

      it('should have the property mark (base name: "mark")', function() {
        // TODO: update the code to test the property mark
        expect(instance).to.have.property('mark');
        // expect(instance.mark).to.be(expectedValueLiteral);
      });

      it('should have the property moneyIntrinsicValue (base name: "moneyIntrinsicValue")', function() {
        // TODO: update the code to test the property moneyIntrinsicValue
        expect(instance).to.have.property('moneyIntrinsicValue');
        // expect(instance.moneyIntrinsicValue).to.be(expectedValueLiteral);
      });

      it('should have the property multiplier (base name: "multiplier")', function() {
        // TODO: update the code to test the property multiplier
        expect(instance).to.have.property('multiplier');
        // expect(instance.multiplier).to.be(expectedValueLiteral);
      });

      it('should have the property netChange (base name: "netChange")', function() {
        // TODO: update the code to test the property netChange
        expect(instance).to.have.property('netChange');
        // expect(instance.netChange).to.be(expectedValueLiteral);
      });

      it('should have the property openInterest (base name: "openInterest")', function() {
        // TODO: update the code to test the property openInterest
        expect(instance).to.have.property('openInterest');
        // expect(instance.openInterest).to.be(expectedValueLiteral);
      });

      it('should have the property openPrice (base name: "openPrice")', function() {
        // TODO: update the code to test the property openPrice
        expect(instance).to.have.property('openPrice');
        // expect(instance.openPrice).to.be(expectedValueLiteral);
      });

      it('should have the property quoteTimeInLong (base name: "quoteTimeInLong")', function() {
        // TODO: update the code to test the property quoteTimeInLong
        expect(instance).to.have.property('quoteTimeInLong');
        // expect(instance.quoteTimeInLong).to.be(expectedValueLiteral);
      });

      it('should have the property rho (base name: "rho")', function() {
        // TODO: update the code to test the property rho
        expect(instance).to.have.property('rho');
        // expect(instance.rho).to.be(expectedValueLiteral);
      });

      it('should have the property securityStatus (base name: "securityStatus")', function() {
        // TODO: update the code to test the property securityStatus
        expect(instance).to.have.property('securityStatus');
        // expect(instance.securityStatus).to.be(expectedValueLiteral);
      });

      it('should have the property settlementType (base name: "settlementType")', function() {
        // TODO: update the code to test the property settlementType
        expect(instance).to.have.property('settlementType');
        // expect(instance.settlementType).to.be(expectedValueLiteral);
      });

      it('should have the property strikePrice (base name: "strikePrice")', function() {
        // TODO: update the code to test the property strikePrice
        expect(instance).to.have.property('strikePrice');
        // expect(instance.strikePrice).to.be(expectedValueLiteral);
      });

      it('should have the property symbol (base name: "symbol")', function() {
        // TODO: update the code to test the property symbol
        expect(instance).to.have.property('symbol');
        // expect(instance.symbol).to.be(expectedValueLiteral);
      });

      it('should have the property theoreticalOptionValue (base name: "theoreticalOptionValue")', function() {
        // TODO: update the code to test the property theoreticalOptionValue
        expect(instance).to.have.property('theoreticalOptionValue');
        // expect(instance.theoreticalOptionValue).to.be(expectedValueLiteral);
      });

      it('should have the property theta (base name: "theta")', function() {
        // TODO: update the code to test the property theta
        expect(instance).to.have.property('theta');
        // expect(instance.theta).to.be(expectedValueLiteral);
      });

      it('should have the property timeValue (base name: "timeValue")', function() {
        // TODO: update the code to test the property timeValue
        expect(instance).to.have.property('timeValue');
        // expect(instance.timeValue).to.be(expectedValueLiteral);
      });

      it('should have the property totalVolume (base name: "totalVolume")', function() {
        // TODO: update the code to test the property totalVolume
        expect(instance).to.have.property('totalVolume');
        // expect(instance.totalVolume).to.be(expectedValueLiteral);
      });

      it('should have the property tradeTimeInLong (base name: "tradeTimeInLong")', function() {
        // TODO: update the code to test the property tradeTimeInLong
        expect(instance).to.have.property('tradeTimeInLong');
        // expect(instance.tradeTimeInLong).to.be(expectedValueLiteral);
      });

      it('should have the property underlying (base name: "underlying")', function() {
        // TODO: update the code to test the property underlying
        expect(instance).to.have.property('underlying');
        // expect(instance.underlying).to.be(expectedValueLiteral);
      });

      it('should have the property underlyingPrice (base name: "underlyingPrice")', function() {
        // TODO: update the code to test the property underlyingPrice
        expect(instance).to.have.property('underlyingPrice');
        // expect(instance.underlyingPrice).to.be(expectedValueLiteral);
      });

      it('should have the property uvExpirationType (base name: "uvExpirationType")', function() {
        // TODO: update the code to test the property uvExpirationType
        expect(instance).to.have.property('uvExpirationType');
        // expect(instance.uvExpirationType).to.be(expectedValueLiteral);
      });

      it('should have the property vega (base name: "vega")', function() {
        // TODO: update the code to test the property vega
        expect(instance).to.have.property('vega');
        // expect(instance.vega).to.be(expectedValueLiteral);
      });

      it('should have the property volatility (base name: "volatility")', function() {
        // TODO: update the code to test the property volatility
        expect(instance).to.have.property('volatility');
        // expect(instance.volatility).to.be(expectedValueLiteral);
      });

    });
  });

}));
